# Generated by Django 5.0.6 on 2025-10-16 20:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarreraSugerida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('area_conocimiento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto_pregunta', models.TextField()),
                ('tipo', models.CharField(choices=[('opcion_multiple', 'Opción múltiple'), ('escala_likert', 'Escala Likert'), ('abierta', 'Abierta')], max_length=20)),
                ('orden', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_id', models.UUIDField()),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('puntuacion_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tiempo_transcurrido', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('duracion_minutos', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creador_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto_opcion', models.TextField()),
                ('valor', models.CharField(blank=True, max_length=50, null=True)),
                ('puntuacion', models.IntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='tests_app.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoCarrera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compatibilidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_app.carrerasugerida')),
                ('resultado_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='tests_app.resultadotest')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('respuesta_texto', models.TextField(blank=True, null=True)),
                ('opcion_seleccionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests_app.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_app.pregunta')),
                ('resultado_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='tests_app.resultadotest')),
            ],
        ),
        migrations.AddField(
            model_name='resultadotest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='tests_app.test'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='tests_app.test'),
        ),
    ]
